### PR TITLE
fix: edit typo and formatting error in developer guide

### PR DESCRIPTION
**Pull request by danielleloh**
edit,
* grammatical errors in case UC03
* formatting errors for extensions in UC03 to indicate where the use case resumes to after an extension case

### CODE REVIEW

**Review by jayllo-c — COMMENTED** [review]
LGTM

**Comment by Zer0Legion** [comment]
LGTM

**Review by Zer0Legion — COMMENTED** [review]
Looks good to me! I find the fix in typos very insightful. Using the Gibb's Reflective Cycle, this is definitely beneficial and will go a long way towards improving our documentation. In the future, we plan to improve documentation.

**Review by delishad21 — COMMENTED** [review]
Nice catch

**Pull request merged**
