### PR TITLE
Update User Guide to include mass email copying feature v1.1

### LINKED ISSUE #88: Update User Guide to include mass email copying feature

### PR DESCRIPTION
**Pull request by jayllo-c**
fixes #88 

Updated the user guide to include the mass email copying feature.

This update ensures that the user guide is up-to-date with the planned
features.

### CODE REVIEW

**Comment by danielleloh** [comment]
looks good to go :)

**Comment by Zer0Legion** [comment]
LGTM

**Comment by Pughal77** [comment]
LGTM!

**Review by Zer0Legion — COMMENTED** [review]
LGTM :)

**Pull request merged**
