### PR TITLE
Update AboutUs.md for Johan

### LINKED ISSUE #56: Update Johan's section in AboutUs.md for v1.1

### PR DESCRIPTION
**Pull request by delishad21**
fixes #56

### CODE REVIEW

**Comment by Zer0Legion** [comment]
LGTM

**Comment by Pughal77** [comment]
LGTM!

**Comment by jayllo-c** [comment]
Looks valid

**Review by Zer0Legion — COMMENTED** [review]
LGTM

**Comment by danielleloh** [comment]
looks good :)

**Pull request merged**
