### PR TITLE
docs: update implementation details in developer guide

### PR DESCRIPTION
**Pull request by danielleloh**
Add sequence diagrams and update implementation details in developer guide for features. The changes are shown below.

## Export Feature
* edit the implementation details to include details on exams
* sequence diagrams

Screenshot 2024-04-11 at 10 02 57 PM
Screenshot 2024-04-11 at 10 03 05 PM

## Sequence Diagrams Added for `addScore`

**Sequence diagram for parsing of `addScore` command:**
Screenshot 2024-04-10 at 4 35 35 PM

**Sequence diagram for execution of `addScore` command:**
Screenshot 2024-04-10 at 4 36 14 PM

## Sequence Diagrams for `deleteScore`

Screenshot 2024-04-10 at 11 17 45 PM

Screenshot 2024-04-10 at 11 18 20 PM

### CODE REVIEW

**Review by Pughal77 — COMMENTED** [review]
The sequence diagrams are accurate and show only what is needed. Good job!

**Review by Zer0Legion — COMMENTED** [review]
Great additions and detailed diagrams. They look correct to me

**Review by delishad21 — COMMENTED** [review]
Diagrams look accurate. Small consideration that isn't directly related to this PR but why are some of the CSVUtil methods static while some are not. Seems to me like all CSVutil methods are meant to be used in a static context

**Review by jayllo-c — COMMENTED** [review]
For the two sequence diagrams modeling the `execute` method of  `exportCommand`, you might wanna use a reference frame and separate diagram notation to show a continuation of the execute method. 

example given in textbook: 
image

Also, right now it can be interpreted as two different execute methods being illustrated since they have different method signatures (one has m as input, the other has no arguments provided).

first execute method:
image

second execute method: 
image

**Pull request merged**
